# Site wide configuration

title: Nikolay Grozev
locale: en_UK
email: nikolay.grozev@gmail.com
description: Staying on top of it.
logo: images/site-logo.jpg
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://nikgrozev.com
disqus:
  shortname: nikgrozev-com
twitter:
  username: nikolaygrozev
google_analytics: "UA-120510914-1"

# Build settings
permalink:   /:year/:month/:day/:title/
markdown: kramdown
remote_theme: "nikolayg/so-simple-theme"
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
weights: "400,400i,700,700i"
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

  # Rouge Highlighter in Kramdown â€º http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1


# Share on social media:
share: true

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

include: [".htaccess", ".well-known"]
exclude: ["*.odg", "*.odt", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site Author
# Icons found at - https://fontawesome.com/icons?d=gallery
author:
  name: Nikolay Grozev
  picture: /images/bio-photo.jpg
  email: nikolay.grozev@gmail.com
  twitter: nikolaygrozev
  links:
    - title: Twitter
      url: https://twitter.com/nikolaygrozev
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/nikolayg
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://linkedin.com/in/nikolaygrozev
      icon: fab fa-linkedin
    - title: Stack Overflow
      url: http://stackoverflow.com/users/3682523/nikolay
      icon: fab fa-stack-overflow
    - title: RSS
      url: http://nikgrozev.com/feed.xml
      icon: fas fa-rss-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/nikolaygrozev
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/nikolayg
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/nikolaygrozev
    icon: fab fa-linkedin
  - title: Stack Overflow
    url: http://stackoverflow.com/users/3682523/nikolay
    icon: fab fa-stack-overflow
  - title: RSS
    url: http://nikgrozev.com/feed.xml
    icon: fas fa-rss-square


